### ISSUE TITLE
Table: add Scales and labels

### ISSUE THREAD

**Issue by anniecherk** [Caleydo/lineage#62] opened 2017-02-22 19:45 UTC
![githubissues_1](https://cloud.githubusercontent.com/assets/4534857/23229163/771e7864-f8fc-11e6-8141-77fa091101c6.jpg)

- [ ] Categorical: label each category
- [ ] Quantitative: mark interval endpoints & user-specified reference value (initialized to the mean)

Incorporates issue #9

**Comment by alexsb** [comment] 2017-03-10 22:25
Partially fixed, partially duplicate of #9

**Closed by alexsb** 2017-03-10 22:25 UTC
Labels: table
