### ISSUE TITLE
Same Sex Couples

### ISSUE THREAD

**Issue by cnobre** [Caleydo/lineage#81] opened 2017-03-08 19:34 UTC
Not sure if this is an artifact of the randomization or a problem in the original data. It's definitely in the data file though. Example below is the founder couple of family 149. 

![screen shot 2017-03-08 at 12 32 57 pm](https://cloud.githubusercontent.com/assets/4120607/23720271/7adf95be-03fb-11e7-8712-08af55656daf.png)

**Comment by alexsb** [comment] 2017-03-08 19:41
Can you check in the original data file? This shouldn't happen with my algorithm. If it does, I'll debug.

**Comment by alexsb** [comment] 2017-03-19 03:57
The problem is that it's the same person twice. Look at the person IDs:

![image](https://cloud.githubusercontent.com/assets/2039375/24078018/d62b9b7a-0c25-11e7-890b-032129de3486.png)

This is a data bug. Nothing we need to do on this (other than maybe loading the cleaner data). Closing.

**Closed by alexsb** 2017-03-19 03:57 UTC
Labels: graph
